# Generated by Django 6.0.4 on 2026-05-08 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('skills_match', models.IntegerField(default=0)),
                ('formatting_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('education_score', models.IntegerField(default=0)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_score', to='analyzer.resume')),
            ],
        ),
    ]
