# Generated by Django 6.0.4 on 2026-05-08 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('match_percentage', models.FloatField(default=0)),
                ('missing_keywords', models.JSONField(default=list)),
                ('matched_keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='analyzer.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_recommendation', models.TextField()),
                ('hindi_recommendation', models.TextField()),
                ('missing_skills', models.JSONField(default=list)),
                ('suggested_certifications', models.JSONField(default=list)),
                ('suggested_projects', models.JSONField(default=list)),
                ('career_improvements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='analyzer.resume')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_audio', models.FileField(blank=True, upload_to='audio/english/')),
                ('hindi_audio', models.FileField(blank=True, upload_to='audio/hindi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='recommendations.recommendation')),
            ],
        ),
    ]
